// js/data.js — Full 78-card Tarot database
// Major Arcana: detailed | Minor Arcana: auto-generated

(function () {
  /* ── Major Arcana detailed ───────────────────────── */
  const MAJOR = [
    { id:0,  name:"The Fool",           nameVi:"Kẻ Ngốc",         number:"0",
      planet:"Sao Thiên Vương", zodiac:"Bảo Bình",
      keywords:["Khởi đầu mới","Tiềm năng","Ngây thơ","Tự do","Dũng cảm"],
      keywordsRev:["Liều lĩnh","Bốc đồng","Mất định hướng"],
      upright:"Khởi đầu mới tràn đầy tiềm năng. Hãy tin vào hành trình, bước đi với trái tim rộng mở.",
      reversed:"Liều lĩnh thiếu suy nghĩ. Hãy dừng lại cân nhắc kỹ trước khi hành động.",
      aspects:{ love:{up:"Tình yêu mới hoặc giai đoạn mới. Hãy mở lòng.",rev:"Thiếu ổn định, quá ngây thơ trong tình cảm."},
        career:{up:"Cơ hội sự nghiệp mới, dám nghĩ dám làm.",rev:"Quyết định hấp tấp, thiếu chuẩn bị."},
        finance:{up:"Cơ hội tài chính mới, cần kế hoạch cụ thể.",rev:"Tránh đầu tư liều lĩnh."},
        health:{up:"Bắt đầu lối sống lành mạnh mới.",rev:"Coi nhẹ sức khỏe, hành động thiếu thận trọng."},
        spiritual:{up:"Hành trình tâm linh mới mẻ.",rev:"Lạc lối trong lý tưởng viển vông."} },
      advice:"Tin tưởng bản thân và bước vào hành trình mới với trái tim rộng mở.",
      numerology:"0 — Vô hạn, tiềm năng thuần túy" },

    { id:1,  name:"The Magician",       nameVi:"Pháp Sư",          number:"I",
      planet:"Sao Thủy", zodiac:"Song Tử & Xử Nữ",
      keywords:["Ý chí mạnh","Tập trung","Kỹ năng","Sáng tạo","Biểu hiện"],
      keywordsRev:["Lừa dối","Lạm dụng","Thiếu trọng tâm"],
      upright:"Bạn có đủ công cụ để biến ước mơ thành hiện thực. Hãy hành động với ý chí mạnh mẽ.",
      reversed:"Cảnh báo lừa dối hoặc lãng phí tài năng. Kiểm tra lại động cơ.",
      aspects:{ love:{up:"Sức hút mạnh mẽ, hãy tự tin thể hiện bản thân.",rev:"Cảnh giác người thao túng cảm xúc."},
        career:{up:"Kỹ năng được công nhận, thời điểm tỏa sáng.",rev:"Tránh dùng thủ thuật."},
        finance:{up:"Tạo thu nhập bằng kỹ năng.",rev:"Cẩn thận kế hoạch tài chính đáng ngờ."},
        health:{up:"Ý chí mạnh cải thiện thể chất.",rev:"Đừng bỏ qua triệu chứng bệnh."},
        spiritual:{up:"Kết nối mạnh với nguồn năng lượng vũ trụ.",rev:"Đừng dùng năng lượng tâm linh tiêu cực."} },
      advice:"Sử dụng tất cả tài năng bạn có. Mọi công cụ đã sẵn sàng.",
      numerology:"1 — Khởi đầu, lãnh đạo, ý chí" },

    { id:2,  name:"The High Priestess", nameVi:"Nữ Tư Tế",         number:"II",
      planet:"Mặt Trăng", zodiac:"Cự Giải",
      keywords:["Trực giác","Bí ẩn","Nội tâm","Tiềm thức","Khôn ngoan"],
      keywordsRev:["Bí mật ẩn","Mất kết nối","Tự dối mình"],
      upright:"Câu trả lời nằm bên trong bạn. Hãy lắng nghe tiếng nói nội tâm và tin vào trực giác.",
      reversed:"Đang bỏ qua trực giác. Có điều gì đó bị che giấu khỏi bạn.",
      aspects:{ love:{up:"Tin vào trực giác trong tình yêu.",rev:"Đang che giấu cảm xúc thật."},
        career:{up:"Nghiên cứu kỹ trước quyết định.",rev:"Thiếu thông tin quan trọng."},
        finance:{up:"Thận trọng trước khi đầu tư.",rev:"Thiếu thông tin tài chính then chốt."},
        health:{up:"Lắng nghe dấu hiệu tinh tế của cơ thể.",rev:"Kiểm tra sức khỏe định kỳ."},
        spiritual:{up:"Thiền định sâu và kết nối tâm linh.",rev:"Mất kết nối nội tâm."} },
      advice:"Câu trả lời bạn tìm kiếm nằm trong chính bạn.",
      numerology:"2 — Cân bằng, trực giác, duality" },

    { id:3,  name:"The Empress",        nameVi:"Nữ Hoàng",         number:"III",
      planet:"Sao Kim", zodiac:"Kim Ngưu & Thiên Bình",
      keywords:["Phong phú","Nuôi dưỡng","Sáng tạo","Tự nhiên","Vẻ đẹp"],
      keywordsRev:["Phụ thuộc","Sáng tạo bị chặn","Mất cân bằng"],
      upright:"Thời điểm sinh sôi và phong phú. Hãy nuôi dưỡng bản thân và những gì bạn trân trọng.",
      reversed:"Sáng tạo bị chặn hoặc phụ thuộc quá mức. Tìm cách nuôi dưỡng bản thân trở lại.",
      aspects:{ love:{up:"Mối quan hệ nở hoa, tràn đầy ấm áp.",rev:"Mối quan hệ phụ thuộc không lành mạnh."},
        career:{up:"Sáng tạo đỉnh cao, thể hiện tài năng.",rev:"Nguồn sáng tạo bị chặn."},
        finance:{up:"Thịnh vượng và tăng trưởng.",rev:"Cần kiểm soát thói quen chi tiêu."},
        health:{up:"Chăm sóc bản thân tốt.",rev:"Cần chú ý hơn đến tự chăm sóc."},
        spiritual:{up:"Kết nối thiên nhiên mang lại bình yên.",rev:"Xa rời bản năng thiên nhiên."} },
      advice:"Nuôi dưỡng bản thân và trân trọng vẻ đẹp trong cuộc sống.",
      numerology:"3 — Sáng tạo, phát triển, phong phú" },

    { id:4,  name:"The Emperor",        nameVi:"Hoàng Đế",         number:"IV",
      planet:"Sao Hỏa", zodiac:"Bạch Dương",
      keywords:["Quyền lực","Kỷ luật","Ổn định","Lãnh đạo","Cấu trúc"],
      keywordsRev:["Độc đoán","Cứng nhắc","Kiểm soát quá mức"],
      upright:"Thiết lập nền tảng vững chắc với kỷ luật và quyết đoán. Ổn định là chìa khóa.",
      reversed:"Độc đoán hoặc kiểm soát quá mức đang gây hại. Hãy mở lòng hơn.",
      aspects:{ love:{up:"Mối quan hệ ổn định có cấu trúc.",rev:"Kiểm soát quá mức trong mối quan hệ."},
        career:{up:"Lãnh đạo hiệu quả, sự nghiệp ổn định phát triển.",rev:"Phong cách lãnh đạo quá cứng nhắc."},
        finance:{up:"Tài chính ổn định nhờ kỷ luật.",rev:"Cần xem lại cách quản lý tài chính."},
        health:{up:"Duy trì thói quen sức khỏe đều đặn.",rev:"Cân bằng kỷ luật và linh hoạt."},
        spiritual:{up:"Kỷ luật tâm linh phát triển bền vững.",rev:"Tránh áp đặt niềm tin lên người khác."} },
      advice:"Thiết lập nền tảng vững chắc và duy trì kỷ luật.",
      numerology:"4 — Ổn định, nền tảng, trật tự" },

    { id:5,  name:"The Hierophant",     nameVi:"Giáo Hoàng",       number:"V",
      planet:"Sao Kim", zodiac:"Kim Ngưu",
      keywords:["Truyền thống","Tôn giáo","Giáo dục","Chuẩn mực","Hướng dẫn"],
      keywordsRev:["Nổi loạn","Giáo điều","Phi chính thống"],
      upright:"Tìm kiếm sự hướng dẫn từ truyền thống và người có kinh nghiệm.",
      reversed:"Đã đến lúc phá vỡ quy tắc cũ và tìm con đường riêng.",
      aspects:{ love:{up:"Mối quan hệ truyền thống, có thể dẫn đến hôn nhân.",rev:"Mối quan hệ phi truyền thống."},
        career:{up:"Tuân theo quy tắc mang lại thành công.",rev:"Cần cách tiếp cận mới táo bạo hơn."},
        finance:{up:"Tuân theo phương pháp tài chính đã chứng minh.",rev:"Cần phá vỡ thói quen cũ."},
        health:{up:"Tin tưởng y học truyền thống.",rev:"Cân nhắc phương pháp điều trị thay thế."},
        spiritual:{up:"Học từ truyền thống và các vị thầy.",rev:"Tìm con đường tâm linh độc lập."} },
      advice:"Học hỏi từ truyền thống nhưng đừng ngại tìm con đường riêng.",
      numerology:"5 — Thay đổi, tự do, thích nghi" },

    { id:6,  name:"The Lovers",         nameVi:"Người Tình",        number:"VI",
      planet:"Sao Thủy", zodiac:"Song Tử",
      keywords:["Tình yêu","Lựa chọn","Hài hòa","Giá trị","Kết nối"],
      keywordsRev:["Mất hài hòa","Lựa chọn sai","Xung đột"],
      upright:"Tình yêu hài hòa và lựa chọn theo đúng giá trị cốt lõi.",
      reversed:"Mất cân bằng, lựa chọn sai lầm hoặc xung đột trong mối quan hệ.",
      aspects:{ love:{up:"Kết nối tâm hồn sâu sắc, mối quan hệ ý nghĩa.",rev:"Mất cân bằng, cần đánh giá lại."},
        career:{up:"Chọn sự nghiệp theo đúng đam mê và giá trị.",rev:"Quyết định khó khăn liên quan công việc."},
        finance:{up:"Hợp tác tài chính tốt.",rev:"Cẩn thận quyết định tài chính chung."},
        health:{up:"Hài hòa thể chất và tinh thần.",rev:"Chú ý sức khỏe tâm thần."},
        spiritual:{up:"Kết nối với nguồn năng lượng thiêng liêng.",rev:"Cân bằng tâm linh và thực tế."} },
      advice:"Chọn thứ phù hợp giá trị cốt lõi. Tình yêu giúp cả hai cùng phát triển.",
      numerology:"6 — Tình yêu, hài hòa, trách nhiệm" },

    { id:7,  name:"The Chariot",        nameVi:"Cỗ Xe",             number:"VII",
      planet:"Mặt Trăng", zodiac:"Cự Giải",
      keywords:["Chiến thắng","Quyết tâm","Kiểm soát","Ý chí","Hành động"],
      keywordsRev:["Mất kiểm soát","Hung hăng","Thiếu hướng đi"],
      upright:"Chiến thắng qua ý chí và kiểm soát bản thân. Bạn đang trên đường thành công.",
      reversed:"Mất kiểm soát hoặc bị xung đột nội tâm chia rẽ.",
      aspects:{ love:{up:"Kiên định theo đuổi tình yêu mục tiêu.",rev:"Kiểm soát quá mức trong mối quan hệ."},
        career:{up:"Tiến bước quyết tâm, thành công gần kề.",rev:"Cần điều chỉnh hướng đi."},
        finance:{up:"Bước mạnh mẽ với kế hoạch tài chính.",rev:"Xem lại định hướng, tránh bốc đồng."},
        health:{up:"Ý chí vượt qua thách thức sức khỏe.",rev:"Cần kiểm soát tốt hơn lối sống."},
        spiritual:{up:"Kiểm soát xung đột nội tâm để tiến bộ.",rev:"Mất la bàn nội tâm, cần thiền định."} },
      advice:"Kiểm soát cả lý trí và cảm xúc để tiến đến mục tiêu.",
      numerology:"7 — Huyền bí, trí tuệ, chiến thắng" },

    { id:8,  name:"Strength",           nameVi:"Sức Mạnh",          number:"VIII",
      planet:"Mặt Trời", zodiac:"Sư Tử",
      keywords:["Dũng cảm","Kiên nhẫn","Đồng cảm","Sức mạnh nội tâm","Tự kiểm soát"],
      keywordsRev:["Yếu đuối","Thiếu tự tin","Lạm dụng"],
      upright:"Sức mạnh nội tâm và lòng dũng cảm. Bạn mạnh mẽ hơn bạn tưởng.",
      reversed:"Đang thiếu tự tin hoặc để cảm xúc tiêu cực kiểm soát.",
      aspects:{ love:{up:"Mối quan hệ xây dựng trên kiên nhẫn và đồng cảm.",rev:"Sợ bị tổn thương trong tình yêu."},
        career:{up:"Đối mặt thách thức bằng lòng dũng cảm.",rev:"Cần tìm lại tự tin ở nơi làm việc."},
        finance:{up:"Kiên nhẫn và kiên định với kế hoạch tài chính.",rev:"Tránh để nỗi sợ kiểm soát quyết định."},
        health:{up:"Sức mạnh nội tâm giúp vượt qua bệnh tật.",rev:"Cần chú ý sức khỏe tâm thần."},
        spiritual:{up:"Kết nối sức mạnh tâm linh với thực tế.",rev:"Cần đối mặt bóng tối nội tâm."} },
      advice:"Sức mạnh thực sự là kiểm soát bản thân bằng tình yêu và đồng cảm.",
      numerology:"8 — Quyền lực, vô hạn, cân bằng" },

    { id:9,  name:"The Hermit",         nameVi:"Ẩn Sĩ",             number:"IX",
      planet:"Sao Thủy", zodiac:"Xử Nữ",
      keywords:["Cô đơn","Hướng nội","Trí tuệ","Tìm kiếm nội tâm","Chỉ dẫn"],
      keywordsRev:["Cô lập quá mức","Rút lui","Từ chối giúp đỡ"],
      upright:"Rút lui tìm ánh sáng bên trong. Đây là lúc suy ngẫm và tìm kiếm sự thật.",
      reversed:"Cô lập quá mức hoặc không sẵn sàng chấp nhận giúp đỡ.",
      aspects:{ love:{up:"Cần hiểu bản thân trước khi tìm tình yêu.",rev:"Cô lập quá mức khỏi tình yêu."},
        career:{up:"Suy ngẫm về định hướng nghề nghiệp.",rev:"Cần hợp tác và kết nối hơn."},
        finance:{up:"Nghiên cứu kỹ trước quyết định tài chính.",rev:"Đừng quá tự lập với quyết định tài chính phức tạp."},
        health:{up:"Nghỉ ngơi và phục hồi, lắng nghe cơ thể.",rev:"Tìm kiếm giúp đỡ khi bệnh."},
        spiritual:{up:"Thiền định và tìm kiếm khai sáng.",rev:"Tránh cô lập tâm linh tiêu cực."} },
      advice:"Dành thời gian một mình lắng nghe tiếng nói nội tâm.",
      numerology:"9 — Hoàn thành, trí tuệ, tâm linh" },

    { id:10, name:"Wheel of Fortune",   nameVi:"Bánh Xe Số Phận",   number:"X",
      planet:"Sao Mộc", zodiac:"Nhân Mã",
      keywords:["Vận mệnh","Thay đổi","Chu kỳ","May mắn","Bước ngoặt"],
      keywordsRev:["Vận rủi","Kháng cự","Chu kỳ tiêu cực"],
      upright:"Bước ngoặt lớn và may mắn đang đến. Hãy đón nhận sự thay đổi.",
      reversed:"Chu kỳ tiêu cực hoặc vận rủi. Hãy thích nghi với sự thay đổi.",
      aspects:{ love:{up:"Bước ngoặt tích cực trong tình yêu.",rev:"Chu kỳ tiêu cực trong tình cảm."},
        career:{up:"Cơ hội nghề nghiệp bất ngờ.",rev:"Thay đổi không mong muốn, cần thích nghi."},
        finance:{up:"May mắn tài chính đang đến.",rev:"Cẩn thận rủi ro tài chính."},
        health:{up:"Chu kỳ tốt bắt đầu.",rev:"Chú ý hơn đến sức khỏe."},
        spiritual:{up:"Tiến hóa tâm linh theo chu kỳ vũ trụ.",rev:"Cần hiểu và chấp nhận chu kỳ tâm linh."} },
      advice:"Đón nhận thay đổi với lòng biết ơn. Mọi thứ đều có chu kỳ.",
      numerology:"10 — Hoàn thành chu kỳ, vận mệnh" },

    { id:11, name:"Justice",            nameVi:"Công Lý",           number:"XI",
      planet:"Sao Kim", zodiac:"Thiên Bình",
      keywords:["Công bằng","Sự thật","Nhân quả","Quyết định","Trách nhiệm"],
      keywordsRev:["Bất công","Trốn tránh trách nhiệm","Thiên vị"],
      upright:"Sự thật và công bằng sẽ thắng. Hãy chịu trách nhiệm về hành động của bạn.",
      reversed:"Bất công hoặc trốn tránh trách nhiệm. Hậu quả đang đến.",
      aspects:{ love:{up:"Mối quan hệ công bằng, hai bên ngang bằng.",rev:"Mất cân bằng quyền lực trong mối quan hệ."},
        career:{up:"Thành công và ghi nhận xứng đáng.",rev:"Đối mặt hậu quả từ quyết định quá khứ."},
        finance:{up:"Giao dịch tài chính công bằng.",rev:"Cẩn thận với hợp đồng và thỏa thuận."},
        health:{up:"Kết quả sức khỏe xứng với nỗ lực.",rev:"Nhân quả sức khỏe từ lối sống."},
        spiritual:{up:"Cân bằng nghiệp quả và học bài học.",rev:"Trốn tránh bài học tâm linh."} },
      advice:"Hãy hành động công bằng và chịu trách nhiệm. Nghiệp quả sẽ cân bằng tất cả.",
      numerology:"11 — Công lý, cân bằng, nhân quả" },

    { id:12, name:"The Hanged Man",     nameVi:"Người Bị Treo",     number:"XII",
      planet:"Sao Hải Vương", zodiac:"Song Ngư",
      keywords:["Chờ đợi","Buông bỏ","Quan điểm mới","Hy sinh","Giác ngộ"],
      keywordsRev:["Trì hoãn","Kháng cự","Hy sinh vô ích"],
      upright:"Hãy dừng lại và nhìn từ góc độ khác. Đôi khi buông bỏ là bước tiến.",
      reversed:"Trì hoãn không cần thiết hoặc từ chối thay đổi quan điểm.",
      aspects:{ love:{up:"Cần nhìn mối quan hệ từ góc độ mới.",rev:"Kẹt trong tình huống cũ, cần buông bỏ."},
        career:{up:"Tạm dừng để xem xét lại phương hướng.",rev:"Trì hoãn quyết định sự nghiệp quan trọng."},
        finance:{up:"Chờ đợi thời điểm đúng để hành động.",rev:"Kẹt trong tình huống tài chính, cần thay đổi."},
        health:{up:"Nghỉ ngơi chủ động để phục hồi.",rev:"Kháng cự cần thiết về thay đổi lối sống."},
        spiritual:{up:"Giai đoạn giác ngộ qua hy sinh và buông bỏ.",rev:"Kháng cự bài học tâm linh."} },
      advice:"Đôi khi không làm gì cũng là hành động. Buông bỏ để tiến lên.",
      numerology:"12 — Hy sinh, giác ngộ, buông bỏ" },

    { id:13, name:"Death",              nameVi:"Cái Chết",           number:"XIII",
      planet:"Sao Hỏa", zodiac:"Thiên Yết",
      keywords:["Chuyển đổi","Kết thúc","Thay đổi","Tái sinh","Buông bỏ quá khứ"],
      keywordsRev:["Kháng cự thay đổi","Trì trệ","Sợ kết thúc"],
      upright:"Một giai đoạn kết thúc để nhường chỗ cho tái sinh. Hãy đón nhận chuyển đổi.",
      reversed:"Kháng cự sự thay đổi cần thiết. Tình trạng trì trệ không thể tiếp tục.",
      aspects:{ love:{up:"Kết thúc một giai đoạn, bắt đầu mới.",rev:"Kháng cự thay đổi cần thiết trong mối quan hệ."},
        career:{up:"Chuyển đổi sự nghiệp lớn đang đến.",rev:"Bám víu công việc cũ không còn phù hợp."},
        finance:{up:"Kết thúc một chu kỳ tài chính, bắt đầu mới.",rev:"Kháng cự thay đổi tài chính cần thiết."},
        health:{up:"Thay đổi lối sống triệt để để cải thiện sức khỏe.",rev:"Từ chối thay đổi thói quen không lành mạnh."},
        spiritual:{up:"Chuyển đổi tâm linh sâu sắc, tái sinh.",rev:"Sợ hãi trước sự chuyển đổi tâm linh."} },
      advice:"Mọi kết thúc đều mang mầm mống của khởi đầu mới. Hãy buông bỏ.",
      numerology:"13 — Chuyển đổi, tái sinh, chu kỳ" },

    { id:14, name:"Temperance",         nameVi:"Điều Độ",           number:"XIV",
      planet:"Sao Mộc", zodiac:"Nhân Mã",
      keywords:["Cân bằng","Kiên nhẫn","Hòa hợp","Điều độ","Tích hợp"],
      keywordsRev:["Mất cân bằng","Thiếu kiên nhẫn","Thái quá"],
      upright:"Cân bằng và hài hòa là chìa khóa. Kiên nhẫn và điều độ trong mọi việc.",
      reversed:"Mất cân bằng hoặc thiếu kiên nhẫn đang gây trở ngại.",
      aspects:{ love:{up:"Mối quan hệ hài hòa, cân bằng tốt.",rev:"Mất cân bằng trong mối quan hệ."},
        career:{up:"Tiếp cận công việc cân bằng và kiên nhẫn.",rev:"Thiếu kiên nhẫn hoặc quá thái quá."},
        finance:{up:"Quản lý tài chính cân bằng và điều độ.",rev:"Chi tiêu thiếu kiểm soát."},
        health:{up:"Lối sống lành mạnh cân bằng.",rev:"Thói quen sức khỏe thiếu nhất quán."},
        spiritual:{up:"Tích hợp các khía cạnh tâm linh và thực tế.",rev:"Mất cân bằng giữa tâm linh và cuộc sống."} },
      advice:"Kiên nhẫn và điều độ. Mọi thứ tốt nhất đều đến qua sự cân bằng.",
      numerology:"14 — Cân bằng, hòa hợp, tích hợp" },

    { id:15, name:"The Devil",          nameVi:"Ác Quỷ",            number:"XV",
      planet:"Sao Thổ", zodiac:"Ma Kết",
      keywords:["Ràng buộc","Cám dỗ","Nghiện ngập","Vật chất","Bóng tối"],
      keywordsRev:["Giải phóng","Thoát khỏi ràng buộc","Nhận thức"],
      upright:"Đang bị ràng buộc bởi cám dỗ hoặc thói quen tiêu cực. Hãy nhận ra và giải phóng.",
      reversed:"Đang trên đường thoát khỏi ràng buộc. Sự giải phóng đang đến.",
      aspects:{ love:{up:"Mối quan hệ dựa trên cám dỗ hoặc phụ thuộc không lành mạnh.",rev:"Thoát khỏi mối quan hệ không lành mạnh."},
        career:{up:"Bị mắc kẹt trong công việc không hài lòng.",rev:"Phá vỡ xiềng xích trong sự nghiệp."},
        finance:{up:"Bị ràng buộc bởi nợ nần hoặc lòng tham.",rev:"Thoát khỏi vấn đề tài chính."},
        health:{up:"Nghiện ngập hoặc thói quen không lành mạnh.",rev:"Đang thoát khỏi thói quen xấu."},
        spiritual:{up:"Bị vật chất che khuất tâm linh.",rev:"Thức tỉnh và nhận ra sự thật."} },
      advice:"Nhận ra ràng buộc của bạn là bước đầu tiên để tự do.",
      numerology:"15 — Vật chất, cám dỗ, bóng tối" },

    { id:16, name:"The Tower",          nameVi:"Ngọn Tháp",         number:"XVI",
      planet:"Sao Hỏa", zodiac:"Không đặc trưng",
      keywords:["Đổ vỡ","Khải thị","Hỗn loạn","Thay đổi đột ngột","Giải phóng"],
      keywordsRev:["Tránh né thảm họa","Kháng cự thay đổi","Trì hoãn"],
      upright:"Đổ vỡ đột ngột dẫn đến giải phóng. Những gì bị phá hủy không còn phục vụ bạn.",
      reversed:"Tránh né hoặc trì hoãn sự thay đổi tất yếu.",
      aspects:{ love:{up:"Mối quan hệ có thể sụp đổ bất ngờ.",rev:"Tránh né sự thật về mối quan hệ."},
        career:{up:"Thay đổi đột ngột trong sự nghiệp hoặc công việc.",rev:"Tránh né thay đổi nghề nghiệp tất yếu."},
        finance:{up:"Tổn thất tài chính bất ngờ, cần lên kế hoạch.",rev:"Kháng cự thay đổi tài chính."},
        health:{up:"Vấn đề sức khỏe bất ngờ cần chú ý.",rev:"Bỏ qua dấu hiệu cảnh báo sức khỏe."},
        spiritual:{up:"Thức tỉnh tâm linh đột ngột.",rev:"Kháng cự sự thức tỉnh cần thiết."} },
      advice:"Đôi khi phải phá hủy để xây dựng lại tốt hơn. Hãy dũng cảm đón nhận.",
      numerology:"16 — Phá hủy, khải thị, tái xây dựng" },

    { id:17, name:"The Star",           nameVi:"Ngôi Sao",          number:"XVII",
      planet:"Sao Thiên Vương", zodiac:"Bảo Bình",
      keywords:["Hy vọng","Cảm hứng","Bình yên","Tái sinh","Niềm tin"],
      keywordsRev:["Mất hy vọng","Tuyệt vọng","Đánh mất niềm tin"],
      upright:"Hy vọng và cảm hứng đang soi sáng con đường. Mọi thứ sẽ tốt hơn.",
      reversed:"Mất hy vọng hoặc tuyệt vọng. Hãy tìm lại ánh sáng.",
      aspects:{ love:{up:"Hy vọng và cảm hứng trong tình yêu.",rev:"Mất niềm tin vào tình yêu."},
        career:{up:"Cảm hứng mới trong sự nghiệp, tương lai tươi sáng.",rev:"Mất động lực trong công việc."},
        finance:{up:"Tình hình tài chính sẽ cải thiện.",rev:"Mất niềm tin vào tương lai tài chính."},
        health:{up:"Phục hồi và tái sinh sức khỏe.",rev:"Mất hy vọng về sức khỏe."},
        spiritual:{up:"Kết nối sâu sắc với vũ trụ và nguồn cảm hứng.",rev:"Mất kết nối tâm linh."} },
      advice:"Hãy giữ vững hy vọng. Ngôi sao dẫn đường luôn ở đó.",
      numerology:"17 — Hy vọng, cảm hứng, niềm tin" },

    { id:18, name:"The Moon",           nameVi:"Mặt Trăng",         number:"XVIII",
      planet:"Mặt Trăng", zodiac:"Song Ngư",
      keywords:["Ảo giác","Sợ hãi","Tiềm thức","Bí ẩn","Lừa dối"],
      keywordsRev:["Giải tỏa sợ hãi","Sự rõ ràng","Chân lý"],
      upright:"Không phải tất cả đều như vẻ ngoài. Hãy tin vào trực giác và cẩn thận ảo giác.",
      reversed:"Sợ hãi đang được giải tỏa. Sự thật đang dần hiện ra.",
      aspects:{ love:{up:"Ảo tưởng về mối quan hệ. Có điều chưa nói.",rev:"Hiểu rõ hơn về mối quan hệ thực sự."},
        career:{up:"Bất ổn và không chắc chắn trong sự nghiệp.",rev:"Sự rõ ràng đang đến trong công việc."},
        finance:{up:"Cẩn thận lừa đảo tài chính.",rev:"Tình hình tài chính rõ ràng hơn."},
        health:{up:"Lo lắng và sợ hãi về sức khỏe.",rev:"Nỗi sợ sức khỏe được giải tỏa."},
        spiritual:{up:"Tiềm thức đang nói chuyện với bạn qua giấc mơ.",rev:"Đang vượt qua ảo giác tâm linh."} },
      advice:"Hãy tin vào trực giác nhưng cẩn thận ảo giác. Sự thật không phải lúc nào cũng rõ ràng.",
      numerology:"18 — Ảo giác, tiềm thức, bí ẩn" },

    { id:19, name:"The Sun",            nameVi:"Mặt Trời",          number:"XIX",
      planet:"Mặt Trời", zodiac:"Sư Tử",
      keywords:["Vui vẻ","Thành công","Tích cực","Năng lượng","Rõ ràng"],
      keywordsRev:["Tiêu cực","Thiếu nhiệt huyết","Thất vọng"],
      upright:"Thành công, vui vẻ và năng lượng tích cực đang đến. Tương lai tươi sáng.",
      reversed:"Thiếu nhiệt huyết hoặc tạm thời âm u. Ánh sáng vẫn sẽ trở lại.",
      aspects:{ love:{up:"Mối quan hệ hạnh phúc và ngập tràn ánh sáng.",rev:"Giai đoạn khó khăn tạm thời trong tình yêu."},
        career:{up:"Thành công rực rỡ trong sự nghiệp.",rev:"Tạm thời thiếu động lực."},
        finance:{up:"Thịnh vượng và tài chính tốt.",rev:"Giai đoạn tài chính khó khăn tạm thời."},
        health:{up:"Sức khỏe tốt, tràn đầy năng lượng.",rev:"Cần chú ý đến sức khỏe và nghỉ ngơi."},
        spiritual:{up:"Giác ngộ, cảm hứng và kết nối thiêng liêng.",rev:"Tạm thời mất kết nối với ánh sáng."} },
      advice:"Hãy cho phép bản thân tỏa sáng. Thế giới cần ánh sáng của bạn.",
      numerology:"19 — Thành công, vui vẻ, tích cực" },

    { id:20, name:"Judgement",          nameVi:"Phán Xét",          number:"XX",
      planet:"Sao Hỏa", zodiac:"Thiên Yết",
      keywords:["Tái sinh","Thức tỉnh","Tha thứ","Đánh giá lại","Kêu gọi"],
      keywordsRev:["Tự phán xét","Nghi ngờ","Bỏ lỡ cơ hội"],
      upright:"Thức tỉnh và tái sinh. Đây là lúc đánh giá lại và lắng nghe tiếng gọi thiêng liêng.",
      reversed:"Tự phán xét quá mức hoặc bỏ lỡ cơ hội quan trọng.",
      aspects:{ love:{up:"Tái sinh trong tình yêu, tha thứ và tiến lên.",rev:"Tự phán xét ngăn cản tình yêu mới."},
        career:{up:"Thức tỉnh nghề nghiệp, tiếng gọi mới.",rev:"Nghi ngờ bản thân trong sự nghiệp."},
        finance:{up:"Đánh giá lại tài chính và tái cơ cấu.",rev:"Tự phán xét về quyết định tài chính quá khứ."},
        health:{up:"Thức tỉnh về sức khỏe, quyết tâm thay đổi.",rev:"Tự trách bản thân về tình trạng sức khỏe."},
        spiritual:{up:"Thức tỉnh tâm linh và nghe tiếng gọi.",rev:"Bỏ qua tiếng gọi tâm linh."} },
      advice:"Tha thứ quá khứ và lắng nghe tiếng gọi thiêng liêng để tiến lên.",
      numerology:"20 — Tái sinh, thức tỉnh, tha thứ" },

    { id:21, name:"The World",          nameVi:"Thế Giới",          number:"XXI",
      planet:"Sao Thổ", zodiac:"Ma Kết",
      keywords:["Hoàn thành","Tích hợp","Thành tựu","Du hành","Toàn vẹn"],
      keywordsRev:["Chưa hoàn thành","Trì hoãn","Thiếu kết thúc"],
      upright:"Hoàn thành một chu kỳ lớn. Thành tựu và sự toàn vẹn trong mọi khía cạnh.",
      reversed:"Gần đến đích nhưng chưa hoàn thành. Hãy kiên trì thêm một chút.",
      aspects:{ love:{up:"Mối quan hệ hoàn chỉnh và viên mãn.",rev:"Cảm giác chưa trọn vẹn trong tình yêu."},
        career:{up:"Đỉnh cao sự nghiệp, thành tựu lớn.",rev:"Sự nghiệp gần đến đỉnh nhưng chưa."},
        finance:{up:"Thịnh vượng trọn vẹn, đạt mục tiêu tài chính.",rev:"Mục tiêu tài chính chưa hoàn thành."},
        health:{up:"Sức khỏe toàn diện và hài hòa.",rev:"Sức khỏe gần tốt nhưng cần thêm nỗ lực."},
        spiritual:{up:"Giác ngộ và hoàn thiện tâm linh.",rev:"Hành trình tâm linh chưa kết thúc."} },
      advice:"Bạn đã đi một chặng đường dài. Hãy tự hào và chuẩn bị cho chu kỳ mới.",
      numerology:"21 — Hoàn thành, toàn vẹn, thành tựu" }
  ];

  /* ── Minor Arcana generator ──────────────────────── */
  const SUITS = [
    { key:'wands',     nameVi:'Gậy',   element:'Lửa',       theme:'hành động, đam mê, sáng tạo', start:22 },
    { key:'cups',      nameVi:'Chén',  element:'Nước',      theme:'cảm xúc, trực giác, mối quan hệ', start:36 },
    { key:'swords',    nameVi:'Kiếm',  element:'Không khí', theme:'trí tuệ, xung đột, sự thật', start:50 },
    { key:'pentacles', nameVi:'Đồng', element:'Đất',       theme:'vật chất, sự nghiệp, sức khỏe', start:64 }
  ];

  const RANKS = [
    { n:'Ace',    nameVi:'Át',   num:'A',  meaning:'Khởi đầu, hạt nhân tiềm năng thuần túy, năng lượng nguyên sơ' },
    { n:'Two',    nameVi:'Hai',  num:'2',  meaning:'Lựa chọn, cân bằng, đối lập, hợp tác' },
    { n:'Three',  nameVi:'Ba',   num:'3',  meaning:'Phát triển, tăng trưởng, cộng đồng, mở rộng' },
    { n:'Four',   nameVi:'Bốn',  num:'4',  meaning:'Ổn định, cơ sở vững chắc, tái tạo năng lượng' },
    { n:'Five',   nameVi:'Năm',  num:'5',  meaning:'Thách thức, xung đột, thay đổi, mất mát' },
    { n:'Six',    nameVi:'Sáu',  num:'6',  meaning:'Phục hồi, cân bằng, hài hòa, di chuyển tiến về phía trước' },
    { n:'Seven',  nameVi:'Bảy',  num:'7',  meaning:'Đánh giá, kiên nhẫn chiến lược, bí ẩn, suy nghĩ' },
    { n:'Eight',  nameVi:'Tám',  num:'8',  meaning:'Hành động nhanh, tiến bộ, kỹ năng, kiểm soát' },
    { n:'Nine',   nameVi:'Chín', num:'9',  meaning:'Gần đến đích, kiên nhẫn, tích lũy, hoàn thiện' },
    { n:'Ten',    nameVi:'Mười', num:'10', meaning:'Hoàn thành chu kỳ, gánh nặng hoặc thành tựu, kết thúc' },
    { n:'Page',   nameVi:'Tiểu Quân', num:'P', meaning:'Thông điệp mới, học hỏi, khám phá, tiềm năng trẻ trung' },
    { n:'Knight', nameVi:'Kỵ Sĩ',    num:'Kn',meaning:'Hành động, thay đổi, chuyển động, nhiệt huyết hoặc thiếu kiên nhẫn' },
    { n:'Queen',  nameVi:'Nữ Hoàng', num:'Q', meaning:'Chín chắn, nuôi dưỡng, kiểm soát bậc thầy và nội lực' },
    { n:'King',   nameVi:'Đức Vua',  num:'K', meaning:'Làm chủ hoàn toàn, quyền lực trưởng thành, lãnh đạo bậc thầy' }
  ];

  const MINOR = [];
  SUITS.forEach(suit => {
    RANKS.forEach((rank, ri) => {
      const imgIdx = suit.start + ri;
      const slug   = `${rank.n}-of-${suit.key.charAt(0).toUpperCase()+suit.key.slice(1)}`;
      // Special case
      const fileName = imgIdx === 62
        ? 'cards/62-Queen-of-Swords-1.jpg'
        : `cards/${imgIdx}-${slug}.jpg`;
      MINOR.push({
        id:       imgIdx,
        name:     `${rank.n} of ${suit.key.charAt(0).toUpperCase()+suit.key.slice(1)}`,
        nameVi:   `${rank.nameVi} ${suit.nameVi}`,
        number:   rank.num,
        arcana:   'minor',
        suit:     suit.key,
        image:    fileName,
        planet:   null,
        zodiac:   null,
        keywords: [`${suit.nameVi}`, `${rank.nameVi}`, suit.theme.split(',')[0].trim(), 'Năng lượng ' + suit.element],
        keywordsRev: ['Chặn', 'Thiếu ' + suit.theme.split(',')[0].trim(), 'Trì trệ'],
        upright:  `${rank.n} of ${suit.key.charAt(0).toUpperCase()+suit.key.slice(1)}: ${rank.meaning}. Liên kết với ${suit.theme} qua nguyên tố ${suit.element}.`,
        reversed: `Khi ngược: năng lượng của ${rank.nameVi} ${suit.nameVi} bị chặn hoặc thái quá. Hãy xem xét lại cách tiếp cận.`,
        aspects: {
          love:     { up:`Trong tình yêu: ${rank.meaning.split(',')[0]}.`, rev:'Xem xét lại cách tiếp cận cảm xúc.' },
          career:   { up:`Trong sự nghiệp: ${rank.meaning.split(',')[0]}.`, rev:'Cần điều chỉnh phương pháp làm việc.' },
          finance:  { up:`Về tài chính: ${rank.meaning.split(',')[0]}.`, rev:'Thận trọng với quyết định tài chính.' },
          health:   { up:`Sức khỏe: ${rank.meaning.split(',')[0]}.`, rev:'Chú ý cân bằng sức khỏe thể chất và tinh thần.' },
          spiritual:{ up:`Tâm linh: ${rank.meaning.split(',')[0]}.`, rev:'Cần kết nối lại với năng lượng tâm linh.' }
        },
        advice:    `Hãy khai thác năng lượng của ${rank.nameVi} ${suit.nameVi}: ${rank.meaning.split(',')[0]}.`,
        numerology:`${rank.num} — ${rank.meaning.split(',')[0]}`
      });
    });
  });

  /* ── Export ──────────────────────────────────────── */
  window.TAROT_DB = [...MAJOR, ...MINOR]; // 22 + 56 = 78 cards

  window.TarotHelper = {
    drawCards(count) {
      const pool = window.TAROT_DB.map(c => ({ ...c, isReversed: Math.random() < 0.3 }));
      // Fisher-Yates shuffle
      for (let i = pool.length - 1; i > 0; i--) {
        const j = Math.floor(Math.random() * (i + 1));
        [pool[i], pool[j]] = [pool[j], pool[i]];
      }
      return pool.slice(0, count);
    },
    getThemeLabel(v) {
      return { love:'Tình Yêu', career:'Sự Nghiệp', finance:'Tài Chính',
               health:'Sức Khỏe', spiritual:'Tâm Linh', general:'Tổng Quát' }[v] || v;
    },
    getSpreadLabels(n) {
      if (n === 1) return ['Hiện Tại'];
      if (n === 3) return ['Quá Khứ', 'Hiện Tại', 'Tương Lai'];
      if (n === 5) return ['Tình Huống', 'Thách Thức', 'Lời Khuyên', 'Ảnh Hưởng', 'Kết Quả'];
      return Array.from({length:n}, (_,i) => `Lá ${i+1}`);
    }
  };
})();
